version: '2'
services:
  exampleservice:
    environment:
      - bootstrap.memory_lock=true
    build: .
    volumes_from:
      - data
    command: cmake --build /home/jonathan/dev/cppPluralCourse/build  --config Debug --target cppPluralCourse -- -j 6
  printingls:
    environment:
      - bootstrap.memory_lock=true
    build: .
    volumes_from:
      - data
    command: /buildEntrypoint.sh
  data:
    build: .
    volumes: 
      - .:/home/jonathan/dev/cppPluralCourse